name: Sync to Hugging Face

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sync GitHub to Hugging Face Hub
        uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: vnscka/pharma-vigil-env
          huggingface_repo_id: ishantk059/pharma-vigil-env
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
          space_sdk: docker
